apiVersion: apps/v1
kind: Deployment
metadata:
  name: basket-api
  namespace: eshop-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basket-api
  template:
    metadata:
      labels:
        app: basket-api
    spec:
      containers:
      - name: basket-api
        image: mcr.microsoft.com/dotnet/samples:eshop-basket-api-latest
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ConnectionStrings__Redis
          value: "redis:6379"
        - name: ConnectionStrings__EventBus
          value: "amqp://guest:guest@rabbitmq:5672"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: basket-api
  namespace: eshop-local
spec:
  selector:
    app: basket-api
  ports:
  - port: 80
    targetPort: 8080