apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api
  namespace: eshop-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-api
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      containers:
      - name: catalog-api
        image: mcr.microsoft.com/dotnet/samples:eshop-catalog-api-latest
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ConnectionStrings__CatalogDB
          value: "Host=postgres;Database=catalogdb;Username=postgres;Password=postgres"
        - name: ConnectionStrings__EventBus
          value: "amqp://guest:guest@rabbitmq:5672"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-api
  namespace: eshop-local
spec:
  selector:
    app: catalog-api
  ports:
  - port: 80
    targetPort: 8080