apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: eshop-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: mcr.microsoft.com/dotnet/samples:eshop-webapp-latest
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ConnectionStrings__EventBus
          value: "amqp://guest:guest@rabbitmq:5672"
        - name: DISABLE_AUTH
          value: "true"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: eshop-local
spec:
  selector:
    app: webapp
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080
  type: NodePort