resources:
- deployment.yaml
- service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: identity-api-env
  literals:
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES=true
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES=true
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY=in_memory
    - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
    - HTTP_PORTS=8080
    - BasketApiClient=http://basket-api:8080
    - OrderingApiClient=http://ordering-api:8080
    - WebhooksApiClient=http://webhooks-api:8080
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
    - OTEL_SERVICE_NAME=identity-api
    - ASPNETCORE_URLS=http://+:8080;
    - ConnectionStrings__identitydb=Host=10.96.199.82;Port=5432;Username=postgres;Password=Pass@word;Database=identitydb;SSL Mode=Disable;Timeout=30;

secretGenerator:
- name: identity-api-secrets
  envs:
  - .identity-api.secrets
