resources:
- deployment.yaml
- service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: postgres-env
  literals:
    - POSTGRES_HOST_AUTH_METHOD=md5
    - POSTGRES_INITDB_ARGS=--auth-host=md5 --auth-local=md5
    - POSTGRES_USER=postgres
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
    - OTEL_SERVICE_NAME=postgres

secretGenerator:
- name: postgres-secrets
  envs:
  - .postgres.secrets
