---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-processor
  labels:
    app: order-processor
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: order-processor
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: order-processor
    spec:
      containers:
      - name: order-processor
        image: docker.io/sebastianruzanowski/order-processor:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: order-processor-env
        - secretRef:
            name: order-processor-secrets
      terminationGracePeriodSeconds: 180